### ISSUE TITLE
smaller margin & dice loss

### ISSUE THREAD

**Issue by Eunpyo127** [perslev/U-Time#13]
Hi!

This is a really nice paper!
I have two questions.

1. Is there any reason for using margin=17 (T=35), and did you test for smaller T?

2. It seems that the formula for genenralized dice loss in your paper seems doesn't match with your implementation in mpunet.evaluate.loss_function. Your implementation seems like below, is it a right expression?
![image](https://user-images.githubusercontent.com/64001061/107192790-6c6da980-6a31-11eb-8626-ea828f6f2492.png)

Can you explain on those two questions?

Thank you.

**Comment by perslev** [comment]
Hi! I am happy you enjoyed the paper, and thank you for your questions. I am sorry my reply comes a bit late.

1) This is a good question, and we have not carefully evaluated other choices of T. One reason for using a relatively large T is to ensure that features with long-range dependencies may be learned without suffering from signifiant boundary effects. For instance, the U-Time model has a theoretical receptive field in the last convolution layer of the encoder sub-network of around 5.5 minutes of 100 Hz signal. With T=35 and 30 second segments the input to U-Time as defined in our paper is 3 times and a bit longer than this maximum receptive field, which we hoped would at least make it possible that such long range dependencies could be learned. However, this number was heuristically defined and it possible that other values lead to better performance in some scenarios. Note finally that increasing T is somewhat similar to increasing the batch size with the (I guess significant) difference that new samples included as T is increased are correlated and not of course not sampled randomly across subjects.

2) Good catch, there definitely seems to be a discrepancy here. We might have made a small error in the notation of the paper - the 'sparse_dice_loss' function at https://github.com/perslev/MultiPlanarUNet/blob/master/mpunet/evaluate/loss_functions.py was the one used.

Let me know if this makes sense or you have further questions :-)

Cheers,
Mathias

**Comment by Eunpyo127** [comment]
Thank you for your detailed response.
It is really helpful.
Have a nice day.
