### ISSUE TITLE
Training on csv input

### ISSUE THREAD

**Issue by alexblnn** [perslev/U-Time#14]
Hello and thanks for this great paper!

I'm currently trying to apply U-Time to sleep apnea detection; the problem I have is that my input data is contained in a CSV file (which regroups different windows of PSG for 22 patients) and not an edf file. Is there a way to use your code with this data format?

Best,

**Comment by perslev** [comment]
Hi! Thanks for your interest in our paper.

It is possible to use other formats than those currently supported, but it requires a little bit of coding. Specifically, you should have a look at the `usleep.io` package: https://github.com/perslev/U-Time/tree/master/utime/io

Specifically, you must implement 3 functions:

1) One that exacts the PSG data as a numpy array. See https://github.com/perslev/U-Time/blob/master/utime/io/psg/psg_extractors.py for examples.

2) One that extracts the hypnogram - or more generally, labels, as in your case. See https://github.com/perslev/U-Time/blob/master/utime/io/hypnogram/hyp_extractors.py for examples.

3) One that extracts a header of information on the PSG channels, sample rates etc. See https://github.com/perslev/U-Time/blob/master/utime/io/header/header_extractors.py for examples.

If this is too much the easiest way, unfortunately, will be to reformat the data to something like HDF5 which is supported.

You are also welcome, if possible, to send me a small sample of the data format that you work with. If it looks relatively standard I can implement these functions for you. Only I cannot guarantee exactly when I will find the time to do so.

I hope this helps.

Cheers,
Mathias

**Comment by alexblnn** [comment]
Hi Mathias and thanks for this detailed and helpful answer!

Good news, I also have the data in the h5 format. For each patient I extracted a PSG .h5 file and a .npy file containing the labels (in my case they are binary, 0 or 1 at each second of the sample indicating apnea events). However I'm now getting the error that my .h5 file does not have a valid header when trying to train UTime.

The data format is as follows: for a given patient, the h5 file contains data of shape (200,72000), which corresponds to 200 windows of 90 seconds sampled at 100Hz with 8 channels. The .npy file contains an array of size (200,90), which corresponds to the labels for each of the 200 windows. Do you have any idea on how I can adapt my data to use your code? I tried a few things, such as renaming the "data" group to "psg" in my h5 files, but it still doesn't work.

Best,
Alexandre
