### ISSUE TITLE
Which tensorflow version are you used?

### ISSUE THREAD

**Issue by Kuanting1224** [perslev/U-Time#2]
Which tensorflow version are you used? I encountered an error for tensorflow.

**Comment by perslev** [comment]
Hi!
It should work with TensorFlow 2.0 or 2.1. Which version did you try? Feel free to share the error message and some system details and I will try to help you out.

**Comment by Kuanting1224** [comment]
The error for tensorflow was corrected.Howevet, I want to try to train a model using multi GPUs. How do I modify the code in the trainer.py file or other files? Thank you.

**Comment by perslev** [comment]
You can train and predict with multiple GPUs by using the --num_GPUs flag. E.g. to train with 2 GPUs, you would call:

ut train --num_GPUs=2

Hope this helps! Sorry, by the way, for the lacking README file. I will try and find time to document this project much better soon.

**Comment by TL730** [comment]
@Kuanting1224 When I installed the environment, an error message prompted that TF GPU needs to be installed, and it couldn't be bypassed. How did you solve it?
