### ISSUE TITLE
Error report of training model

### ISSUE THREAD

**Issue by TL730** [perslev/U-Time#20]
“ut train --num_GPUs=0 --preprocessed --seed 123”

then :

" writing to the existing file." % file_path)
OSError: Logging path: /usr/local/anaconda3/condabin/demo/logs/log.txt already exists. Initialize Logger with overwrite_existing=True or append_existing=True to overwrite or continue writing to the existing file.

**Comment by perslev** [comment]
Hi,

Use the `--overrite` flag to overwrite the current data in the project folder. E.g.,

`ut train --num_GPUs=0 --preprocessed --overwrite`

**Comment by TL730** [comment]
The reply is so fast. I'll try it right away, 👍

**Comment by TL730** [comment]
"The 'eager' data loading queue currently does not support datasets with "
NotImplementedError: The 'eager' data loading queue currently does not support datasets with the 'load_time_channel_sampling_groups' or 'access_time_channel_sampling_groups' attributes set. If you want to train using random channel combinations, either pre-process the data using the 'ut preprocess' command and then re-run training using 'ut train --preprocessed', or run training with the limitation queue loader using the '--train_queue_type limitation' command.

**Comment by TL730** [comment]
Using the following two commands, both report the same error:
ut train --num_GPUs=0 --preprocessed --overwrite
ut train --num_GPUs=0 --preprocessed --seed 123

"The 'eager' data loading queue currently does not support datasets with "
NotImplementedError: The 'eager' data loading queue currently does not support datasets with the 'load_time_channel_sampling_groups' or 'access_time_channel_sampling_groups' attributes set. If you want to train using random channel combinations, either pre-process the data using the 'ut preprocess' command and then re-run training using 'ut train --preprocessed', or run training with the limitation queue loader using the '--train_queue_type limitation' command.

**Comment by TL730** [comment]
Using the following two commands, both report the same error:
ut train --num_GPUs=0 --preprocessed --overwrite
ut train --num_GPUs=0 --preprocessed --seed 123

"The 'eager' data loading queue currently does not support datasets with "
NotImplementedError: The 'eager' data loading queue currently does not support datasets with the 'load_time_channel_sampling_groups' or 'access_time_channel_sampling_groups' attributes set. If you want to train using random channel combinations, either pre-process the data using the 'ut preprocess' command and then re-run training using 'ut train --preprocessed', or run training with the limitation queue loader using the '--train_queue_type limitation' command.
