### ISSUE TITLE
After the dataset is downloaded, it can be used directly, right?

### ISSUE THREAD

**Issue by TL730** [perslev/U-Time#27]
Hello! I ran demo on a Mac without GPU, and here's the end result. 

<img width="449" alt="截屏2021-06-07 下午9 07 30" src="https://user-images.githubusercontent.com/45458131/121021880-68317d00-c7d4-11eb-8022-97e00ff65e16.png">

I would like to ask:

After the dataset is downloaded, it can be used directly, right? Just use your commands to segment, preprocess and train? No additional data processing? In the supplementary materials of this paper, the sampling rate and filtering of each data set are the data set's own? For example, sedf-sc & sedf-st: EEG and EOG signals were recorded at 100 Hz. DCSM: EEG and EOG signals were recorded at 256 Hz and bandpass filtered to interval 0.3 Hz - 70 Hz (3dB limits)

**Comment by TL730** [comment]
I'm going to start downloading data sets for model training.

In addition to the preprocessing command given by you, there is no need for additional special preprocessing? For example: what are the requirements for data format? Each of the 13 datasets listed has its own number of records. Do you use the total number of records in each dataset? If not all, how do you choose?
According to your data segmentation command, is data segmentation random?

best，
Lei

**Comment by TL730** [comment]
What's the result of the model you trained with multiple datasets?

How much epoch and time do you need to train

**Comment by perslev** [comment]
Hi,

Please refer to our paper for details on evaluation etc.
https://www.nature.com/articles/s41746-021-00440-5

Cheers,
Mathias
