### ISSUE TITLE
Your article says that you only need one EEG and one EOG channel. Will key information be missed?

### ISSUE THREAD

**Issue by TL730** [perslev/U-Time#29]
According to some literatures, vertex sharp transient, spindle wave and K-complex mainly appear in specific brain regions, or most significantly in a certain brain region. Your article says that you only need one EEG and one EOG channel. Will key information be missed? How to prove that it won't?

Spindle activity was best recorded by central electrode, while K complex and K complex were the best δ The best recording method is frontal electrode (Rodenbeck et al., 2006; Silber et al.，2007）； On the one hand, the integration of frontal, central and occipital leads improved the reliability of IRR. In fact, the reliability of the arousal score was particularly low in the absence of increased submental EMG activity.

**Comment by perslev** [comment]
Hi TL730,

This is a very interesting question, which we also wondered ourselves. It is very possible that the model is not always able to detect certain features / events in the available channels. It was an open question when we designed this system if it would be able to learn robust sleep staging based on just the 2 input channels (with randomly varying electrode positions even). However, based on the extensive evaluation we have done it seems the model is either 1) able to robustly detect such patterns even in channels where humans find it difficult / are not able to, or 2) relies on other features entirely when scoring. It is possible that the model (e.g., using its ability to consider quite long-range patterns in the signals both back and forth in time) has learned features that are more robustly observable across channels. We are not really sure yet and  hope to learn more from future studies.

Cheers,
Mathias
