### ISSUE TITLE
One question about dataset structure

### ISSUE THREAD

**Issue by xiaoshijiu1999** [perslev/U-Time#30]
I directly downloaded the complete SEDF data set without code.The data in the dataset is organized in the following format(all the files are in one folder):
![image](https://user-images.githubusercontent.com/50627109/121988310-a75f5f80-cdcc-11eb-8a10-376134723379.png)
I wonder if I have to process the data in the following format(the PSG file and corresponding Hypnogram are in a separate folder):
![image](https://user-images.githubusercontent.com/50627109/121988379-c1993d80-cdcc-11eb-885f-9aeb468dd084.png)

**Comment by perslev** [comment]
Hi!

Yes, the files must be organized into folders with one folder for each subject/recording (could be multiple records from one subject, each in their own directory).

Cheers
Mathias
