### ISSUE TITLE
It seems that the confusion matrix and F1 score are not ideal.

### ISSUE THREAD

**Issue by TL730** [perslev/U-Time#32]
We used all the data of individual data sets for training, and it seems that the confusion matrix and F1 score are not ideal.
![22](https://user-images.githubusercontent.com/45458131/122715038-e2650580-d29a-11eb-91af-2bf34eca01ef.jpg)
![1](https://user-images.githubusercontent.com/45458131/122715047-e5f88c80-d29a-11eb-8c2e-cab40fc184e2.jpg)

**Comment by perslev** [comment]
Hi TL730,

I need a few additional details. What experiment have you been running here? Which exact datasets are you referring to? From the above image it seems you are evaluating the model at epoch 5, which is likely much too early for the model to have converged properly.

Cheers,
Mathias
