### ISSUE TITLE
AttributeError: UTime object has no attribute 'loss_functions'

### ISSUE THREAD

**Issue by ploe24** [perslev/U-Time#37]
I'm getting this error at the end of the first epoch when using the "MCP_Clean" callback .
Without (comment this callback), it doesn't crash.
(Tensorflow 2.4)
![NoLossFunction](https://user-images.githubusercontent.com/88377575/129010623-a02c4895-90e6-46b3-99b8-d942636b0a53.png)

**Comment by perslev** [comment]
Hi,

Thanks for reporting this. You should be able to temporarily avoid this issue by downgrading to the recommended TF version 2.1. However, I will look into a better solution in 1 or 2 weeks when back from other activities.

Cheers,
Mathias

**Comment by perslev** [comment]
Now fixed, see https://github.com/perslev/U-Time/issues/39.
