### ISSUE TITLE
ValueError: Input tensors to a UTime must come from 'tf.keras.Input'. Received: None (missing previous layer metadata)

### ISSUE THREAD

**Issue by ploe24** [perslev/U-Time#38]
This error occurs while evaluating (even when using the SEDF example dataset)
![InputTensors](https://user-images.githubusercontent.com/88377575/129007934-c3e49479-c4b8-46eb-9f26-0398d3bc5bf3.png)

**Comment by perslev** [comment]
Hi,

Thanks for reporting this. Which version of TensorFlow do you use?
I will look into the issue in 1 or 2 weeks as I am preoccupied with other activities until then.

Cheers,
Mathias

**Comment by ploe24** [comment]
Hi,
Thanks for your reply.
We are using TensorFlow 2.4.0

**Comment by ploe24** [comment]
Just figured out, that this error only occures when using "ut evaluate" with the "--one_shot" argument. Without it works fine (at least does not crash).

**Comment by perslev** [comment]
This should be fixed in newer versions. Please try to pull the latest version and let me know if you still experience this issue :)
