### ISSUE TITLE
Pre-trained weights

### ISSUE THREAD

**Issue by skjerns** [perslev/U-Time#44]
Even though we do have access to the NSRR datasets, we currently don't have any GPU clusters to train the model. Do you also provide pre-trained weights for U-Sleep?

**Comment by perslev** [comment]
Hi skjerns,

We do not currently provide the weights (although they are available for free usage via https://sleep.ai.ku.dk). However, this may change in the future and then I will let you know.

For now, I suggest you use the server, or if this is not feasible for your specific project, please reach out to me directly on email.

Cheers,
Mathias
