### ISSUE TITLE
Can I stage sleep on the website?

### ISSUE THREAD

**Issue by TL730** [perslev/U-Time#45]
It says on sleep.ai.ku.dk:Select a polysomnography (PSG) file from your computer to upload for sleep staging.

Must it be a PSG? I just collected an EEG channel and an ophthalmic channel. Can I stage sleep on the website?

**Comment by TL730** [comment]
Excuse me, 
1. Can the impedance exceed 10K Ω? 
2. Is it OK to use TXT format documents? Can I use BDF format? How to convert to EDF format?

**Comment by TL730** [comment]
The EEG signal I collected is about 100k Ω, OK?

**Comment by perslev** [comment]
Hi TL730,

Yes, you can use the webserver to score your file as long as you have recorded a single EEG and EOG channel. You can use the following pseudocode to create an .h5 file, which you may uploaded to the server:

´´´
import numpy as np
from utime.utils.scriptutils import to_h5_file

# Load EEG channel here as [N] shaped array
eeg = ...
print(eeg.shape)
> (384000,)   # for instance

eog = ...   # same for EOG

# Stack to [N, 2] shaped array
data = np.stack([eeg, eog]).T
print(data.shape)
> (384000, 2)   # for instance

# Set your sample rate
sample_rate = 256   # for instance

# Save to .h5 file
to_h5_file(
    out_path='my_data.h5',
    data=data,
    channel_names=['EEG', 'EOG'],
    sample_rate=sample_rate,
    date=None
)
´´´

Cheers,
Mathias
