### ISSUE TITLE
 The name of the dataset to download. Must be one of: sedf_sc, sedf_st, dcsm, phys

### ISSUE THREAD

**Issue by emleeee** [perslev/U-Time#47]
Hi! 
I want to know the reason of" The name of the dataset to download. Must be one of:sedf_sc, sedf_st, dcsm, phys"
And "ut fetch --dataset dcsm --out_dir [LOCAL_PATH] --N_first --no_preprocessing" what should i use after"--N_first"
Thanks very much!

**Comment by perslev** [comment]
Hi emleee

The `ut fetch` command is only implemented for those few datasets currently. Is there some other specific dataset that you are interested in? I might be able to find time to implement them for download with `fetch` too.

As for `--N_first` this argument is optional and allows you to specify a number of sleep studies to download. E.g., `--N_first 10` would fetch only the first 10 samples. You can drop the argument entirely to just download everything.

Cheers
Mathias

**Comment by emleeee** [comment]
Hi Mathias

Thanks for your reply and it's truly useful.

I don't have interest dataset and i just want to know how to process the data. Now i plan to learn your code first.

But i have another problem now. I've run  "ut fetch --dataset sedf_sc --out_dir datasets/sedf_sc"   to download the data successfully .   But when i ran "ut extract" command, it showed that "Found 0 files matching glob statement
". I can't solve this problem. Is there some wrong in the command "ut fetch --dataset sedf_sc --out_dir datasets/sedf_sc"?

Thank you very much.
emleee

**Comment by emleeee** [comment]
Hi Mathias

The screenshot of this question is:

 ut extract --file_regex '/datasets/sedf_st/sleep-edf-extended/ST*/*PSG.edf' --out_dir '/datasets/sedf_st/processed/sedf-st/' --resample 128 --channels 'EEG Fpz-Cz' 'EEG Pz-Oz' 'EOG horizontal' --rename Fpz-Cz Pz-Oz EOG

Args dump: {'file_regex': '/datasets/sedf_st/sleep-edf-extended/ST*/*PSG.edf', 'out_dir': '/datasets/sedf_st/processed/sedf-st/', 'channels': ['EEG Fpz-Cz', 'EEG Pz-Oz', 'EOG horizontal'], 'rename_channels': ['Fpz-Cz', 'Pz-Oz', 'EOG'], 'resample': 128, 'overwrite': False, 'use_dir_names': False}

Found 0 files matching glob statement

I don't know what i can do to this problem.Could you please give me some advice?

THX a lot!!!

emleee
