### ISSUE TITLE
how to use postprocessing strategy? thx!

### ISSUE THREAD

**Issue by ljyljy** [perslev/U-Time#49]
Hello, could you please show me how to implement the "postprocessing"  functions? Could you provide a demo if it's convenient for you? 
thank you very much!!!
:)

**Comment by perslev** [comment]
Hi

Sorry for my late reply. Do you mean the hypnogram smoothing functions in `utime.postprocessing`? These functions are never actually used by the `utime` package itself, but you may use them if you want to smooth a hypnogram by replacing certain sub-hypnograms (e.g., a triplet of 3 contagious stages) with some other. For instance, if you wanted to replace all triplets `REM` -> `W` -> `REM` you could do:

```python
import numpy as np
from utime.postprocessing.transition_rules import apply_substitution_rules

raw_hyp = np.asarray(['W', 'W', 'N1', 'N2', 'REM', 'REM', 'W', 'REM', 'REM'])
rules = [
    (('REM', 'W', 'REM'), ('REM', 'REM', 'REM')),
]
processed_hyp = apply_substitution_rules(raw_hyp, rules)
print(processed_hyp)

>> ['W' 'W' 'N1' 'N2' 'REM' 'REM' 'REM' 'REM' 'REM']
```

Note that replacement rules are applied in the order the appear in the `rules` list. You can use longer or shorter replacement rules too.

Cheers
Mathias
