### ISSUE TITLE
Cant startv training

### ISSUE THREAD

**Issue by maksimovkonstantin** [perslev/U-Time#5]
Hi!

I cannot start training got next traceback
raceback (most recent call last):
  File "/home/ubuntu/U-Time/utime/dataset/sleep_study.py", line 503, in _load_with_any_in
    load_channels=channel_set or None)
  File "/home/ubuntu/U-Time/utime/io/high_level_file_loaders.py", line 44, in load_psg
    data_dir=os.path.split(psg_file_path)[0])
  File "/home/ubuntu/U-Time/utime/io/extractors/psg_extractors.py", line 105, in extract_psg_data
    len(load_channels), load_channels, psg_data.shape
utime.errors.ChannelNotFoundError: Unexpected channel loading error. Should have loaded 1 channels (['EEG Fpz-Cz']), but the PSG array has shape (7926000, 2). There might be an error in the code. Please rais an issue on GitHub.

**Comment by perslev** [comment]
Hi! I am not able to reproduce this error in my environment, would you mind sharing yours? E.g. output of `pip freeze` or `conda env export`.

Thanks!

**Comment by maksimovkonstantin** [comment]
absl-py==0.9.0
aiofiles==0.4.0
amqp==2.5.2
appnope==0.1.0
astor==0.8.1
attrs==19.3.0
backcall==0.1.0
bcrypt==3.1.7
billiard==3.6.3.0
bleach==3.1.3
celery==4.4.0
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
click==7.1.1
contextvars==2.4
cycler==0.10.0
dataclasses==0.7
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
fastapi==0.46.0
filelock==3.0.12
fire==0.3.0
gast==0.3.3
gdown==3.10.3
google-pasta==0.2.0
grpcio==1.27.2
h11==0.9.0
h5py==2.10.0
httptools==0.0.13
idna==2.9
imageio==2.8.0
immutables==0.11
importlib-metadata==1.5.0
iniherit==0.3.9
ipdb==0.12.2
ipykernel==5.2.0
ipython==7.13.0
ipython-genutils==0.2.0
jedi==0.16.0
Jinja2==2.11.1
joblib==0.14.1
json5==0.9.3
jsonschema==3.2.0
jupyter-client==6.1.0
jupyter-core==4.6.3
jupyterlab==2.0.1
jupyterlab-server==1.0.7
Keras==2.3.1
Keras-Applications==1.0.8
keras-nalu==1.3.0
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
kombu==4.6.8
llvmlite==0.31.0
Markdown==3.2.1
MarkupSafe==1.1.1
matplotlib==3.1.2
mistune==0.8.4
mne==0.20.3
MultiPlanarUNet==0.2.3
nbconvert==5.6.1
nbformat==5.0.4
networkx==2.4
nibabel==3.1.0
notebook==6.0.3
numba==0.48.0
numpy==1.17.3
opencv-python==4.2.0.32
packaging==20.3
pandas==0.25.2
pandocfilters==1.4.2
parso==0.6.2
passlib==1.7.2
pdfkit==0.6.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.0.0
plotly==4.6.0
prometheus-client==0.7.1
prompt-toolkit==3.0.4
protobuf==3.11.3
psutil==5.7.0
psycopg2-binary==2.8.4
ptyprocess==0.6.0
pycparser==2.20
pydantic==1.4
Pygments==2.6.1
PyJWT==1.7.1
pyparsing==2.4.6
pyrsistent==0.15.7
PySocks==1.7.1
python-dateutil==2.8.1
python-dotenv==0.10.5
python-multipart==0.0.5
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==19.0.0
requests==2.23.0
retrying==1.3.3
ruamel.base==1.0.0
ruamel.yaml==0.16.10
ruamel.yaml.clib==0.2.0
scikit-image==0.16.2
scikit-learn==0.22.2.post1
scipy==1.4.1
Send2Trash==1.5.0
Shapely==1.7.0
six==1.14.0
sklearn==0.0
sqlparse==0.3.1
starlette==0.12.9
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
text-unidecode==1.3
tornado==6.0.4
tqdm==4.43.0
traitlets==4.3.3
urllib3==1.25.9
-e git+https://github.com/perslev/U-Time@f4038e8d385254e8223fb05edb158417c0f9212f#egg=utime
uvicorn==0.11.1
uvloop==0.14.0
vine==1.3.0
wcwidth==0.1.9
webencodings==0.5.1
websockets==8.1
Werkzeug==1.0.0
wrapt==1.12.1
xlrd==1.2.0
xlwt==1.3.0
yoyo-migrations==7.0.0
zipp==3.1.0

**Comment by maksimovkonstantin** [comment]
But I think some problems with channels because traceback says that psg files have more channels inside, I did all steps from readme and everything worked till training

**Comment by scxixixi** [comment]
I met the same error.

**Comment by fMeow** [comment]
`mne` should under `0.20`. Install mne 0.19 should help.
