### ISSUE TITLE
wrong extract_hypno command on shhs.md

### ISSUE THREAD

**Issue by jiminbot20** [perslev/U-Time#59]
https://github.com/perslev/U-Time/blob/d2c5cfe2359cd4beb02fd60fdae2b2313f11bc19/resources/usleep_dataset_prep/shhs.md?plain=1#L10

**_extract_** should be fixed to **_extract_hypno_**

**Comment by perslev** [comment]
Thank you, fixed in 1cc7e38737639aa7f8d738576c16b4b3f3000ff7
