### ISSUE TITLE
why use conv2d in U-Time/utime/models/utime.py?

### ISSUE THREAD

**Issue by wangjinzhuo** [perslev/U-Time#6]
Hi Perslev

I read your paper and Supplementary Table S.2. It seems all the conv and pooling operations are conducted in 1D. Is there anything I misunderstand?

Many thanks,
Jinzhuo

**Comment by perslev** [comment]
Hi, good question! This is purely for technical reasons. When we implemented this project the 1d conv CUDA operation was much slower than its 2d counterpart when running on GPU (at least on our systems). We therefore implemented our models to compute on 1d signals with an additional 'dummy' dimension. An input of shape [N, C] would instead essentially be processed as an [N, 1, C] input with 2d convolution kernels of size  [K, 1] applied along the first dimension.

Hope this clarifies.

**Comment by wangjinzhuo** [comment]
Thank you for your explanations. Understand it now.

Another issue I want to ask is the source of 6 public datasets used in your paper. I found it is difficult to locate them on web because many original links are not available now. Can you please provide the links you used to download those datasets?

Thank you
