### ISSUE TITLE
Timeseries segmentation using unsupervised data?

### ISSUE THREAD

**Issue by sangramkapre** [perslev/U-Time#7]
Hi, I enjoyed reading your paper and understood (to some extent) how it works on supervised data. I have seen couple of other research papers using UNet for unsupervised segmentation of time series data. Are you also planning to implement unsupervised segmentation using your network architecture?

**Comment by perslev** [comment]
Hi sangramkapre! Sorry for my very late response. We do not currently have plans to use U-Time in the unsupervised setting, but I would be interested to read some of the papers you mention. Please feel free to forward any that you find interesting to me. Thanks!
